In [1]:
import json
import pandas as pd

# Specify the correct encoding (usually 'utf-8')
json_file = 'laliga_merge.json'

with open(json_file, 'r', encoding='utf-8') as file:
    try:
        data = json.load(file)
        df = pd.DataFrame(data)
        print(df)
    except json.JSONDecodeError as e:
        print(f"Invalid JSON format: {e}")
    except UnicodeDecodeError as e:
        print(f"Unicode decoding error: {e}")

        get                                         parameters errors  \
0   players   {'league': '140', 'page': '1', 'season': '2023'}     []
1   players  {'league': '140', 'page': '27', 'season': '2023'}     []
2   players  {'league': '140', 'page': '12', 'season': '2023'}     []
3   players  {'league': '140', 'page': '15', 'season': '2023'}     []
4   players  {'league': '140', 'page': '22', 'season': '2023'}     []
5   players  {'league': '140', 'page': '20', 'season': '2023'}     []
6   players  {'league': '140', 'page': '23', 'season': '2023'}     []
7   players  {'league': '140', 'page': '28', 'season': '2023'}     []
8   players  {'league': '140', 'page': '11', 'season': '2023'}     []
9   players  {'league': '140', 'page': '25', 'season': '2023'}     []
10  players  {'league': '140', 'page': '24', 'season': '2023'}     []
11  players  {'league': '140', 'page': '16', 'season': '2023'}     []
12  players  {'league': '140', 'page': '19', 'season': '2023'}     []
13  players  {'league': '140', 'page': '18', 'season': '2023'}     []
14  players  {'league': '140', 'page': '21', 'season': '2023'}     []
15  players  {'league': '140', 'page': '10', 'season': '2023'}     []
16  players  {'league': '140', 'page': '17', 'season': '2023'}     []
17  players   {'league': '140', 'page': '2', 'season': '2023'}     []
18  players  {'league': '140', 'page': '29', 'season': '2023'}     []
19  players  {'league': '140', 'page': '26', 'season': '2023'}     []
20  players  {'league': '140', 'page': '14', 'season': '2023'}     []
21  players  {'league': '140', 'page': '13', 'season': '2023'}     []
22  players  {'league': '140', 'page': '36', 'season': '2023'}     []
23  players  {'league': '140', 'page': '32', 'season': '2023'}     []
24  players  {'league': '140', 'page': '35', 'season': '2023'}     []
25  players  {'league': '140', 'page': '40', 'season': '2023'}     []
26  players  {'league': '140', 'page': '31', 'season': '2023'}     []
27  players  {'league': '140', 'page': '30', 'season': '2023'}     []
28  players  {'league': '140', 'page': '34', 'season': '2023'}     []
29  players  {'league': '140', 'page': '37', 'season': '2023'}     []
30  players  {'league': '140', 'page': '33', 'season': '2023'}     []
31  players  {'league': '140', 'page': '38', 'season': '2023'}     []
32  players   {'league': '140', 'page': '4', 'season': '2023'}     []
33  players   {'league': '140', 'page': '3', 'season': '2023'}     []
34  players  {'league': '140', 'page': '42', 'season': '2023'}     []
35  players   {'league': '140', 'page': '7', 'season': '2023'}     []
36  players  {'league': '140', 'page': '41', 'season': '2023'}     []
37  players  {'league': '140', 'page': '44', 'season': '2023'}     []
38  players  {'league': '140', 'page': '39', 'season': '2023'}     []
39  players   {'league': '140', 'page': '5', 'season': '2023'}     []
40  players  {'league': '140', 'page': '43', 'season': '2023'}     []
41  players   {'league': '140', 'page': '6', 'season': '2023'}     []
42  players  {'league': '140', 'page': '45', 'season': '2023'}     []
43  players   {'league': '140', 'page': '8', 'season': '2023'}     []
44  players   {'league': '140', 'page': '9', 'season': '2023'}     []

    results                        paging  \
0        20   {'current': 1, 'total': 45}
1        20  {'current': 27, 'total': 45}
2        20  {'current': 12, 'total': 45}
3        20  {'current': 15, 'total': 45}
4        20  {'current': 22, 'total': 45}
5        20  {'current': 20, 'total': 45}
6        20  {'current': 23, 'total': 45}
7        20  {'current': 28, 'total': 45}
8        20  {'current': 11, 'total': 45}
9        20  {'current': 25, 'total': 45}
10       20  {'current': 24, 'total': 45}
11       20  {'current': 16, 'total': 45}
12       20  {'current': 19, 'total': 45}
13       20  {'current': 18, 'total': 45}
14       20  {'current': 21, 'total': 45}
15       20  {'current': 10, 'total': 45}
16       20  {'current': 17, 'total': 45}
17       20   {'current': 2, 'total': 45}
18       20  {'current': 29, 'total': 45}
19       20  {'current': 26, 'total': 45}
20       20  {'current': 14, 'total': 45}
21       20  {'current': 13, 'total': 45}
22       20  {'current': 36, 'total': 45}
23       20  {'current': 32, 'total': 45}
24       20  {'current': 35, 'total': 45}
25       20  {'current': 40, 'total': 45}
26       20  {'current': 31, 'total': 45}
27       20  {'current': 30, 'total': 45}
28       20  {'current': 34, 'total': 45}
29       20  {'current': 37, 'total': 45}
30       20  {'current': 33, 'total': 45}
31       20  {'current': 38, 'total': 45}
32       20   {'current': 4, 'total': 45}
33       20   {'current': 3, 'total': 45}
34       20  {'current': 42, 'total': 45}
35       20   {'current': 7, 'total': 45}
36       20  {'current': 41, 'total': 45}
37       20  {'current': 44, 'total': 45}
38       20  {'current': 39, 'total': 45}
39       20   {'current': 5, 'total': 45}
40       20  {'current': 43, 'total': 45}
41       20   {'current': 6, 'total': 45}
42       10  {'current': 45, 'total': 45}
43       20   {'current': 8, 'total': 45}
44       20   {'current': 9, 'total': 45}

                                             response
0   [{'player': {'id': 83, 'name': 'A. Danjuma', '...
1   [{'player': {'id': 372, 'name': 'Éder Militão'...
2   [{'player': {'id': 134, 'name': 'Juan Miranda'...
3   [{'player': {'id': 385, 'name': 'Óliver Torres...
4   [{'player': {'id': 737, 'name': 'Odriozola', '...
5   [{'player': {'id': 20, 'name': 'A. Witsel', 'f...
6   [{'player': {'id': 414, 'name': 'Omar Mascarel...
7   [{'player': {'id': 1264, 'name': 'Y. Sabaly', ...
8   [{'player': {'id': 59, 'name': 'Álvaro Morata'...
9   [{'player': {'id': 330, 'name': 'José Callejón...
10  [{'player': {'id': 47536, 'name': 'Martín Pasc...
11  [{'player': {'id': 176, 'name': 'É. Lamela', '...
12  [{'player': {'id': 898, 'name': 'Ander Herrera...
13  [{'player': {'id': 452, 'name': 'Fernando', 'f...
14  [{'player': {'id': 29, 'name': 'J. Oblak', 'fi...
15  [{'player': {'id': 1830, 'name': 'Gonçalo Paci...
16  [{'player': {'id': 608, 'name': 'L. Boyé', 'fi...
17  [{'player': {'id': 111, 'name': 'Rony Lopes', ...
18  [{'player': {'id': 521, 'name': 'R. Lewandowsk...
19  [{'player': {'id': 744, 'name': 'Brahim Díaz',...
20  [{'player': {'id': 39, 'name': 'S. Savić', 'fi...
21  [{'player': {'id': 131, 'name': 'Jorge Cuenca'...
22  [{'player': {'id': 570, 'name': 'F. Cervi', 'f...
23  [{'player': {'id': 158, 'name': 'P. Gazzaniga'...
24  [{'player': {'id': 143, 'name': 'Carles Aleñá'...
25  [{'player': {'id': 340, 'name': 'S. Babić', 'f...
26  [{'player': {'id': 531, 'name': 'D. Blind', 'f...
27  [{'player': {'id': 126, 'name': 'Iñaki Peña', ...
28  [{'player': {'id': 48, 'name': 'Saúl', 'firstn...
29  [{'player': {'id': 1926, 'name': 'J. Aidoo', '...
30  [{'player': {'id': 19352, 'name': 'Sergi Canós...
31  [{'player': {'id': 536, 'name': 'D. Sinkgraven...
32  [{'player': {'id': 46, 'name': 'Vitolo', 'firs...
33  [{'player': {'id': 755, 'name': 'Jaime Seoane'...
34  [{'player': {'id': 403, 'name': 'M. Nastasić',...
35  [{'player': {'id': 614, 'name': 'C. Bravo', 'f...
36  [{'player': {'id': 937, 'name': 'Rubén Sobrino...
37  [{'player': {'id': 129, 'name': 'Chumi', 'firs...
38  [{'player': {'id': 166, 'name': 'J. Foyth', 'f...
39  [{'player': {'id': 15, 'name': 'T. Delaney', '...
40  [{'player': {'id': 2459, 'name': 'D. Machís', ...
41  [{'player': {'id': 6048, 'name': 'B. Cufré', '...
42  [{'player': {'id': 119, 'name': 'R. Falcao', '...
43  [{'player': {'id': 667, 'name': 'M. Depay', 'f...
44  [{'player': {'id': 2208, 'name': 'C. Grenier',...

In [2]:
df.head()

,get,parameters,errors,results,paging,response
0,players,"{'league': '140', 'page': '1', 'season': '2023'}",[],20,"{'current': 1, 'total': 45}","[{'player': {'id': 83, 'name': 'A. Danjuma', '..."
1,players,"{'league': '140', 'page': '27', 'season': '2023'}",[],20,"{'current': 27, 'total': 45}","[{'player': {'id': 372, 'name': 'Éder Militão'..."
2,players,"{'league': '140', 'page': '12', 'season': '2023'}",[],20,"{'current': 12, 'total': 45}","[{'player': {'id': 134, 'name': 'Juan Miranda'..."
3,players,"{'league': '140', 'page': '15', 'season': '2023'}",[],20,"{'current': 15, 'total': 45}","[{'player': {'id': 385, 'name': 'Óliver Torres..."
4,players,"{'league': '140', 'page': '22', 'season': '2023'}",[],20,"{'current': 22, 'total': 45}","[{'player': {'id': 737, 'name': 'Odriozola', '..."

In [3]:
df['response'][0][0]

{'player': {'id': 83,
  'name': 'A. Danjuma',
  'firstname': 'Arnaut',
  'lastname': 'Danjuma Adam Groeneveld',
  'age': 26,
  'birth': {'date': '1997-01-31', 'place': 'Lagos', 'country': 'Nigeria'},
  'nationality': 'Netherlands',
  'height': '178 cm',
  'weight': '74 kg',
  'injured': False,
  'photo': 'https://media.api-sports.io/football/players/83.png'},
 'statistics': [{'team': {'id': 533,
    'name': 'Villarreal',
    'logo': 'https://media.api-sports.io/football/teams/533.png'},
   'league': {'id': 140,
    'name': 'La Liga',
    'country': 'Spain',
    'logo': 'https://media.api-sports.io/football/leagues/140.png',
    'flag': 'https://media.api-sports.io/flags/es.svg',
    'season': 2023},
   'games': {'appearences': None,
    'lineups': None,
    'minutes': None,
    'number': None,
    'position': 'Attacker',
    'rating': None,
    'captain': False},
   'substitutes': {'in': None, 'out': None, 'bench': None},
   'shots': {'total': None, 'on': None},
   'goals': {'total': None, 'conceded': None, 'assists': None, 'saves': None},
   'passes': {'total': None, 'key': None, 'accuracy': None},
   'tackles': {'total': None, 'blocks': None, 'interceptions': None},
   'duels': {'total': None, 'won': None},
   'dribbles': {'attempts': None, 'success': None, 'past': None},
   'fouls': {'drawn': None, 'committed': None},
   'cards': {'yellow': None, 'yellowred': None, 'red': None},
   'penalty': {'won': None,
    'commited': None,
    'scored': None,
    'missed': None,
    'saved': None}}]}

In [4]:
import pandas as pd

# Assuming df is already loaded with data and has a 'response' column

all_players_stats = []  # This will store the flattened data for all players across all rows

# Iterate over each row in the DataFrame
for row in df['response']:
    # Iterate over each player dictionary in the list of players for this row
    for i in row:
        players = {}  # Dictionary to store flattened player data

        # Flatten player details
        for j in i['player'].keys():
            players[j] = i['player'][j]
        
        # Flatten statistics details (assuming there might be multiple statistics entries, but we'll use the first one for simplicity)
        for k in i['statistics'][0].keys():
            if isinstance(i['statistics'][0][k], dict):
                for l in i['statistics'][0][k].keys():
                    players[k+'_'+l] = i['statistics'][0][k][l]
            else:
                players[k] = i['statistics'][0][k]

        # Append the flattened data to the list
        all_players_stats.append(players)

In [5]:
# Convert the list of player dictionaries to a DataFrame
laliga_players_df = pd.DataFrame(all_players_stats)

# Display the resulting DataFrame
laliga_players_df.head()

,id,name,firstname,lastname,age,birth,nationality,height,weight,injured,...,fouls_drawn,fouls_committed,cards_yellow,cards_yellowred,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved
0,83,A. Danjuma,Arnaut,Danjuma Adam Groeneveld,26,"{'date': '1997-01-31', 'place': 'Lagos', 'coun...",Netherlands,178 cm,74 kg,False,...,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN
1,274,E. Cavani,Edinson Roberto,Cavani Gómez,36,"{'date': '1987-02-14', 'place': 'Salto', 'coun...",Uruguay,184 cm,71 kg,False,...,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN
2,634,David Silva,David Josué,Jiménez Silva,37,"{'date': '1986-01-08', 'place': 'Arguineguín',...",Spain,170 cm,67 kg,False,...,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN
3,1584,Loren Morón,Lorenzo Jesús,Morón García,30,"{'date': '1993-12-30', 'place': 'Marbella', 'c...",Spain,188 cm,66 kg,False,...,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN
4,1699,Iborra,Vicente,Iborra de la Fuente,35,"{'date': '1988-01-16', 'place': 'Moncada', 'co...",Spain,190 cm,80 kg,False,...,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN

In [6]:
laliga_players_df.shape

(890, 57)

In [7]:
# Extract the 'date', 'place', and 'country' from the 'birth' dictionary
laliga_players_df['birth_date'] = laliga_players_df['birth'].apply(lambda x: x.get('date') if isinstance(x, dict) else None)
laliga_players_df['birth_place'] = laliga_players_df['birth'].apply(lambda x: x.get('place') if isinstance(x, dict) else None)
laliga_players_df['birth_country'] = laliga_players_df['birth'].apply(lambda x: x.get('country') if isinstance(x, dict) else None)

# Drop the original 'birth' column
laliga_players_df.drop(columns=['birth'], inplace=True)

# Display the resulting DataFrame
laliga_players_df.head()

,id,name,firstname,lastname,age,nationality,height,weight,injured,photo,...,cards_yellowred,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved,birth_date,birth_place,birth_country
0,83,A. Danjuma,Arnaut,Danjuma Adam Groeneveld,26,Netherlands,178 cm,74 kg,False,https://media.api-sports.io/football/players/8...,...,NaN,NaN,None,None,NaN,NaN,NaN,1997-01-31,Lagos,Nigeria
1,274,E. Cavani,Edinson Roberto,Cavani Gómez,36,Uruguay,184 cm,71 kg,False,https://media.api-sports.io/football/players/2...,...,NaN,NaN,None,None,NaN,NaN,NaN,1987-02-14,Salto,Uruguay
2,634,David Silva,David Josué,Jiménez Silva,37,Spain,170 cm,67 kg,False,https://media.api-sports.io/football/players/6...,...,NaN,NaN,None,None,NaN,NaN,NaN,1986-01-08,Arguineguín,Spain
3,1584,Loren Morón,Lorenzo Jesús,Morón García,30,Spain,188 cm,66 kg,False,https://media.api-sports.io/football/players/1...,...,NaN,NaN,None,None,NaN,NaN,NaN,1993-12-30,Marbella,Spain
4,1699,Iborra,Vicente,Iborra de la Fuente,35,Spain,190 cm,80 kg,False,https://media.api-sports.io/football/players/1...,...,NaN,NaN,None,None,NaN,NaN,NaN,1988-01-16,Moncada,Spain

In [8]:
#laliga_players_df.to_csv('laliga_player23.csv',index=False)

In [9]:
laliga_players_df.drop_duplicates(subset='id',keep='first')

,id,name,firstname,lastname,age,nationality,height,weight,injured,photo,...,cards_yellowred,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved,birth_date,birth_place,birth_country
0,83,A. Danjuma,Arnaut,Danjuma Adam Groeneveld,26,Netherlands,178 cm,74 kg,False,https://media.api-sports.io/football/players/8...,...,NaN,NaN,None,None,NaN,NaN,NaN,1997-01-31,Lagos,Nigeria
1,274,E. Cavani,Edinson Roberto,Cavani Gómez,36,Uruguay,184 cm,71 kg,False,https://media.api-sports.io/football/players/2...,...,NaN,NaN,None,None,NaN,NaN,NaN,1987-02-14,Salto,Uruguay
2,634,David Silva,David Josué,Jiménez Silva,37,Spain,170 cm,67 kg,False,https://media.api-sports.io/football/players/6...,...,NaN,NaN,None,None,NaN,NaN,NaN,1986-01-08,Arguineguín,Spain
3,1584,Loren Morón,Lorenzo Jesús,Morón García,30,Spain,188 cm,66 kg,False,https://media.api-sports.io/football/players/1...,...,NaN,NaN,None,None,NaN,NaN,NaN,1993-12-30,Marbella,Spain
4,1699,Iborra,Vicente,Iborra de la Fuente,35,Spain,190 cm,80 kg,False,https://media.api-sports.io/football/players/1...,...,NaN,NaN,None,None,NaN,NaN,NaN,1988-01-16,Moncada,Spain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,403241,Gaizka García,Gaizka,García Vázquez,19,Spain,192 cm,None,False,https://media.api-sports.io/football/players/4...,...,0.0,0.0,None,None,0.0,0.0,0.0,2005-02-17,Vitoria-Gasteiz,Spain
886,412739,Fran Árbol,Francisco Pedro,Árbol Córdoba,18,Spain,185 cm,70 kg,False,https://media.api-sports.io/football/players/4...,...,0.0,0.0,None,None,0.0,0.0,0.0,2006-06-30,Granada,Spain
887,436202,E. Bello,Eghosa Augustine,Bello,20,Nigeria,195 cm,None,False,https://media.api-sports.io/football/players/4...,...,0.0,0.0,None,None,0.0,0.0,NaN,2004-03-17,Benin City,Nigeria
888,437600,Paco Sanz,Paco,Sanz Mora,20,Spain,188 cm,None,False,https://media.api-sports.io/football/players/4...,...,0.0,0.0,None,None,0.0,0.0,NaN,2004-11-15,None,Spain
889,438131,Egoitz Muñoz,Egoitz,Muñoz Larrea,20,Spain,179 cm,73 kg,False,https://media.api-sports.io/football/players/4...,...,0.0,0.0,None,None,0.0,0.0,NaN,2004-04-14,None,Spain